# Database Configuration
spring.datasource.url=jdbc:mysql://db:3306/ferrecontrol_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
spring.jpa.properties.hibernate.jdbc.batch_size=5000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.username=ferre_user
spring.datasource.password=ferre_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Configuration
server.port=8081

# External API Configuration (CodArt)
external.api.token=q4PKT1JrYozQHbTIakLGQS2thuCf2Ebu4GwfFHBlQpmPJYKyM0YqPVG0IRKm
external.api.base-url=https://api-codart.cgrt.org/api/v1/consultas
